name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

     

      # Backend - Express Server 
      - name: Install dependencies for backend
        working-directory: ./express-server
        run: npm install  
